[package]
name = "bom_ba"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html5ever = "0.26.0"
markup5ever = "0.11.0"
reqwest = { version = "0.11.15", features = ["blocking"] }
soup = "0.5.1"
